# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a769a80ebf157ea4fce4c3ecd1be48966ca018a5915213c3bd77941bf0f0395acdd0b43a0f03da788fd69e5fc0cbed8531cd73e707bd578a37ad3acd619a8cae

test:
  secret_key_base: 132ca6de8c8864fbdf4848b41a08b1c586a0144600b2e3beff43c8c08cd1d57f8e84d398ea214da59a4198921dc175a16be122d16846b9a23cec72d49bf3b696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
